import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../../store/useAuthStore';
import { HiMail, HiLockClosed, HiUser, HiPhone, HiArrowRight, HiIdentification, HiTruck, HiBriefcase } from 'react-icons/hi';
import { MdEngineering } from 'react-icons/md';
import './Auth.css';

const LOGO_URL = 'https://res.cloudinary.com/dwmjz9csc/image/upload/v1788114865/0e7be675-4f29-45fc-9ef5-a9809350eaa9.png';
const VEHICLE_TYPES = ['JCB / Backhoe', 'Excavator', 'Bulldozer', 'Crane', 'Dump Truck / Tipper', 'Road Roller', 'Concrete Mixer', 'Forklift', 'Tractor', 'Water Tanker', 'Plumber', 'Electrician', 'Carpenter', 'Painter', 'AC Technician', 'Other'];
const EXPERIENCE_OPTIONS = ['Less than 1 year', '1–3 years', '3–5 years', '5–10 years', '10+ years'];

export default function Register({ role: fixedRole = 'customer' }) {
  const role = fixedRole === 'worker' ? 'worker' : 'customer';
  const [step, setStep] = useState(1);
  const [form, setForm] = useState({ name: '', email: '', phone: '', password: '', confirm: '' });
  const [workerForm, setWorkerForm] = useState({ vehicleType: '', licenseNo: '', experience: '', aadhar: '', address: '' });
  const [otp, setOtp] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const { register } = useAuthStore(); const navigate = useNavigate();
  const f = key => ({ value: form[key], onChange: e => setForm(p => ({ ...p, [key]: e.target.value })) });
  const w = key => ({ value: workerForm[key], onChange: e => setWorkerForm(p => ({ ...p, [key]: e.target.value })) });

  const handleFormSubmit = e => { e.preventDefault(); setError(''); if (form.password !== form.confirm) return setError('Passwords do not match'); if (form.password.length < 6) return setError('Password must be at least 6 characters'); setStep(role === 'worker' ? 2 : 3); };
  const handleWorkerNext = e => { e.preventDefault(); setError(''); if (!workerForm.vehicleType) return setError('Please select a service/vehicle type'); if (!workerForm.licenseNo) return setError('License/ID number is required'); setStep(3); };
  const handleVerifyOtp = async e => { e.preventDefault(); setError(''); if (otp !== '123456') return setError('Invalid OTP. Use 123456 for demo'); setLoading(true); await new Promise(r => setTimeout(r, 400)); const data = { name: form.name, email: form.email, phone: form.phone, password: form.password, role, ...(role === 'worker' && { vehicle: `${workerForm.vehicleType} • ${workerForm.licenseNo}`, experience: workerForm.experience, address: workerForm.address, rating: 4.5, jobsDone: 0, available: false }) }; const result = register(data); setLoading(false); if (result.error) return setError(result.error); navigate(`/${role}/signin`, { replace: true }); };
  const STEPS = role === 'worker' ? ['Details', 'Worker Info', 'OTP'] : ['Details', 'OTP'];

  return <div className="auth-page"><div className="auth-card">
    <Link to="/" className="auth-brand" aria-label="Clean America home"><img src={LOGO_URL} alt="Clean America" className="auth-brand-logo" /></Link>
    <div className="reg-steps">{STEPS.map((s, i) => <div key={s} className={`reg-step ${i < step - 1 ? 'done' : i === step - 1 ? 'active' : ''}`}><div className="rs-dot">{i < step - 1 ? '✓' : i + 1}</div><span>{s}</span></div>)}</div>
    {step === 1 && <><h1>{role === 'worker' ? 'Worker Registration' : 'Create Customer Account'}</h1><p className="auth-sub">Enter your basic details</p><form onSubmit={handleFormSubmit}><label>Full Name<div className="input-wrap"><HiUser className="input-icon" /><input placeholder="Your full name" {...f('name')} required /></div></label><label>Email<div className="input-wrap"><HiMail className="input-icon" /><input type="email" placeholder="you@example.com" {...f('email')} required /></div></label><label>Phone<div className="input-wrap"><HiPhone className="input-icon" /><input type="tel" placeholder="+91 98765 43210" {...f('phone')} required /></div></label><label>Password<div className="input-wrap"><HiLockClosed className="input-icon" /><input type="password" placeholder="Min. 6 characters" {...f('password')} required /></div></label><label>Confirm Password<div className="input-wrap"><HiLockClosed className="input-icon" /><input type="password" placeholder="Repeat password" {...f('confirm')} required /></div></label>{error && <div className="auth-error">⚠️ {error}</div>}<button type="submit" className="auth-submit"><span>{role === 'worker' ? 'Next: Worker Details' : 'Send OTP'}</span><HiArrowRight style={{ width: 16, height: 16 }} /></button></form></>}
    {step === 2 && role === 'worker' && <><h1>Worker Details</h1><p className="auth-sub">Tell us about your skills & equipment</p><form onSubmit={handleWorkerNext}><label>Service / Vehicle Type<div className="input-wrap"><HiTruck className="input-icon" /><select className="auth-select" value={workerForm.vehicleType} onChange={e => setWorkerForm(p => ({ ...p, vehicleType: e.target.value }))} required><option value="">Select type...</option>{VEHICLE_TYPES.map(v => <option key={v} value={v}>{v}</option>)}</select></div></label><label>License / Vehicle Reg. No.<div className="input-wrap"><HiIdentification className="input-icon" /><input placeholder="KA 05 AB 1234" {...w('licenseNo')} required /></div></label><label>Years of Experience<div className="input-wrap"><HiBriefcase className="input-icon" /><select className="auth-select" value={workerForm.experience} onChange={e => setWorkerForm(p => ({ ...p, experience: e.target.value }))} required><option value="">Select experience...</option>{EXPERIENCE_OPTIONS.map(o => <option key={o} value={o}>{o}</option>)}</select></div></label><label>Aadhar / ID Number<div className="input-wrap"><HiIdentification className="input-icon" /><input placeholder="XXXX XXXX XXXX" {...w('aadhar')} /></div></label><label>Current Address<div className="input-wrap"><MdEngineering className="input-icon" /><input placeholder="City, State" {...w('address')} /></div></label>{error && <div className="auth-error">⚠️ {error}</div>}<button type="submit" className="auth-submit"><span>Send OTP</span><HiArrowRight style={{ width: 16, height: 16 }} /></button></form></>}
    {step === 3 && <><h1>Verify Mobile</h1><p className="auth-sub">OTP sent to {form.phone}</p><form onSubmit={handleVerifyOtp}><div className="otp-info"><HiPhone className="otp-info-icon" /><div><strong>OTP sent to {form.phone}</strong><p>Enter the 6-digit code to verify</p></div></div><label>Enter OTP<div className="input-wrap"><HiLockClosed className="input-icon" /><input type="text" placeholder="123456" value={otp} onChange={e => setOtp(e.target.value.replace(/\D/g, '').slice(0, 6))} maxLength={6} required autoFocus /></div></label><div className="otp-hint">💡 Demo OTP: <strong>123456</strong></div>{error && <div className="auth-error">⚠️ {error}</div>}<button type="submit" className="auth-submit" disabled={loading || otp.length !== 6}>{loading ? 'Creating account...' : <><span>Verify & Create Account</span><HiArrowRight style={{ width: 16, height: 16 }} /></>}</button><button type="button" className="auth-back" onClick={() => { setStep(role === 'worker' ? 2 : 1); setOtp(''); setError(''); }}>← Back</button></form></>}
    <p className="auth-switch">Already have an account? <Link to={`/${role}/signin`}>Sign in</Link></p>
  </div><div className="auth-visual"><div className="av-content"><div className="av-icon">🚜</div><h2>{role === 'worker' ? 'Earn with Clean America' : 'Join Clean America'}</h2><p>{role === 'worker' ? 'Join verified workers earning through Clean America.' : 'Get verified operators, live tracking, and instant booking for your construction needs.'}</p><div className="av-features"><div>✅ Verified operators</div><div>✅ Real-time GPS tracking</div><div>✅ Transparent pricing</div><div>✅ 24/7 support</div></div></div></div></div>;
}
