import { useState } from 'react'
import './Home.css'
const fallback='https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=900&q=80'
export default function Home({ services, setPage, setSelectedService, logo }) {
 const [query,setQuery]=useState(''); const [imageErrors,setImageErrors]=useState({}); const list=services.filter(s=>s.name.toLowerCase().includes(query.toLowerCase()))
 const open=s=>{setSelectedService(s);setPage('book')}; const image=(s)=>imageErrors[s.id]?fallback:s.image
 const fail=id=>setImageErrors(x=>({...x,[id]:true}))
 return <main className="page-view home-view"><header className="page-brand"><div><img className="brand-logo" src={logo} alt="Clean America Dallas"/><span><strong>Clean America</strong><b>Dallas</b></span></div><button onClick={()=>setPage('profile')} aria-label="Open profile">J</button></header><section className="home-intro"><div><p>Hello, Jennifer 👋</p><h1>What service do you need today?</h1><small>Reliable outdoor cleaning, right when you need it.</small></div><i>J</i></section><div className="home-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search services..." aria-label="Search services"/><button onClick={()=>setQuery('')} aria-label="Clear search">{query?'×':'⌕'}</button></div><section className="home-section"><div className="section-title"><div><small>QUICK BOOK</small><h2>Featured services</h2></div><button onClick={()=>setPage('book')}>View all</button></div><div className="feature-grid">{list.slice(0,2).map((s,i)=><button className={'feature-card '+(i===0?'featured':'')} key={s.id} onClick={()=>open(s)}><div className="feature-image"><img src={image(s)} onError={()=>fail(s.id)} alt=""/></div><strong>{s.name}</strong><small>Starting at</small><b>${s.price}</b></button>)}</div></section><section className="home-section"><div className="section-title"><div><small>POPULAR</small><h2>Services near you</h2></div></div><div className="service-feed">{list.slice(2).map(s=><button key={s.id} className="service-feed-item" onClick={()=>open(s)}><img src={image(s)} onError={()=>fail(s.id)} alt=""/><span><strong>{s.name}</strong><small>{s.description}</small><b>From ${s.price}</b></span><i>›</i></button>)}</div>{!list.length&&<div className="empty-search">No services found. Try another search.</div>}</section></main>
}
