import { useState } from 'react'
import './Profile.css'

const items=[
 {key:'personal',title:'Personal information',desc:'Name, email and phone number'},
 {key:'addresses',title:'Saved addresses',desc:'Manage your service locations'},
 {key:'payments',title:'Payment methods',desc:'Cards and preferred payment'},
 {key:'notifications',title:'Notifications',desc:'Booking and service updates'},
 {key:'support',title:'Help & support',desc:'FAQs and customer support'}
]
export default function Profile({setPage,onLogout}){
 const [open,setOpen]=useState(null),[saved,setSaved]=useState(false),[name,setName]=useState('Jennifer Williams'),[email,setEmail]=useState('jennifer@example.com'),[phone,setPhone]=useState('+1 (214) 555-0188'),[address,setAddress]=useState('1200 Main St, Dallas, TX'),[notifications,setNotifications]=useState(true),[card,setCard]=useState('Visa ending in 4242')
 const save=e=>{e.preventDefault();setSaved(true);setTimeout(()=>setSaved(false),1800)}
 const panel=key=>{if(key==='personal')return <form onSubmit={save}><label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone number<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><button className="settings-save">Save changes</button></form>;if(key==='addresses')return <form onSubmit={save}><label>Service address<textarea value={address} onChange={e=>setAddress(e.target.value)} rows="3"/></label><button className="settings-save">Save address</button></form>;if(key==='payments')return <div className="preference-row"><div><strong>{card}</strong><small>Primary payment method</small></div><button onClick={()=>setCard(card.endsWith('4242')?'Visa ending in 1111':'Visa ending in 4242')}>Change</button></div>;if(key==='notifications')return <div className="preference-row"><div><strong>Booking notifications</strong><small>{notifications?'You will receive booking updates and reminders.':'Notifications are currently paused.'}</small></div><button className="status-button" onClick={()=>setNotifications(!notifications)}>{notifications?'Enabled':'Disabled'}</button></div>;return <div className="support-content"><strong>How can we help?</strong><p>Find answers or contact our support team about bookings, payments and services.</p><div><button onClick={()=>alert('FAQ section opened.')}>Browse FAQs</button><button onClick={()=>alert('Support request started.')}>Contact support</button></div></div>}
 return <main className="page-view profile-view"><header className="list-header"><div><small>ACCOUNT</small><h1>Profile</h1></div><button onClick={()=>setPage('home')} aria-label="Back to home">×</button></header><section className="profile-hero"><div className="profile-avatar">JW</div><div className="profile-identity"><strong>{name}</strong><span>{email}</span><span>{phone}</span></div><button className="edit-profile" onClick={()=>setOpen(open==='personal'?null:'personal')}>Edit profile</button></section><section className="settings-card">{items.map(item=><div className={'settings-item '+(open===item.key?'open':'')} key={item.key}><button className="settings-trigger" onClick={()=>setOpen(open===item.key?null:item.key)}><span><strong>{item.title}</strong><small>{item.desc}</small></span><b>›</b></button>{open===item.key&&<div className="settings-panel">{panel(item.key)}</div>}</div>)}</section><button className="logout-btn" onClick={()=>{if(window.confirm('Log out of your Clean America Dallas account?'))onLogout?.()}}>Log out</button>{saved&&<div className="profile-toast">Changes saved</div>}</main>
}
